### PR TITLE
Account for old default pgbackrest config file not existing

### LINKED ISSUE #307: pgbackrest.conf has moved
**Describe the issue:**

With pgBackRest 2.x, the conf file moved from `/etc/pgbackrest.conf` to `/etc/pgbackrest/pgbackrest.conf`. Currently the code assumes the old location continues to exist (either as a file or a symlink to the 2.x file) but this isn't always true. I'm seeing these errors in the pg logs:
```
2022-11-10 19:38:27.133 UTC [127.0.0.1(53356)] [ppid=,pid=23393]: [l-3] user=ccp_monitoring,db=postgres,app=[unknown],qid=3694949039461716331,qstate=00000 LOG:  connection authorized: user=ccp_monitoring database=postgres application_name=pgmonitor_global
grep: /etc/pgbackrest.conf: No such file or directory
2022-11-10 19:38:27.208 UTC [127.0.0.1(53356)] [ppid=,pid=23393]: [l-4] user=ccp_monitoring,db=postgres,app=pgmonitor_global,qid=-5104950606484512206,qstate=P0001 ERROR:  No backups being returned from pgbackrest info command
```

**Describe the expected behavior:**

Test for /etc/pgbackrest/pgbackrest.conf, fail back to /etc/pgbackrest.conf if the oprior wasn't found, then fail entirely if neither was found

**Tell us about your environment:**  
- pgMonitor version:  4.8
- Container or non-container:  non
- Container name / image:  
- Operating System for non-container:  u20
- PostgreSQL Version:  15

### PR DESCRIPTION
**Pull request by keithf4**
# Description  

The pgbackrest-info.sh script still assumes the old `/etc/pgbackrest.conf` file exists. Account for that not being the case since the default changed in backrest 2.x

Fixes #307 

Depends on #  

## Type of change  
Please check all options that are relevant  
- [x] Bug fix (change which fixes an issue)  
- [ ] Feature (change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update only  

# How Has This Been Tested?  
**Tested Configuration**:  
- [ ] Ansible, Specify version(s):  
- Installation method:  
    - [ ] Binary install from source, version:  
    - [ ] OS package repository, distro, and version:  
    - [ ] Local package server, version:  
    - [x] Custom-built package, version:  4.8RC1 test package
    - [ ] Other:  
- [x] PostgreSQL, Specify version(s):  15
- [ ] docs tested with hugo version(s):  

Tested with playbook(s):  

# Checklist:  
- [x] My changes generate no new lint warnings  
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

### CODE REVIEW

File: postgres_exporter/linux/pgbackrest-info.sh [hunk 1]
```diff
@@ -15,7 +15,12 @@ SYSTEM_ID=$1
 [ -f /etc/pgmonitor.conf ] && . /etc/pgmonitor.conf
 
 if [ ${BACKREST_AUTOCONFIG_STANZAS:-0} -gt 0 ]; then
-  BACKREST_STANZAS=$(grep '^\[' /etc/pgbackrest.conf /etc/pgbackrest/  -rh |sort -u |grep -v ':\|global' |sed 's/\[\|\]//g' | tr '\n' ' ' )
+  if [ -f "/etc/pgbackrest.conf" ]; then
+    # Account for old default config file location
+    BACKREST_STANZAS=$(grep '^\[' /etc/pgbackrest.conf /etc/pgbackrest/  -rh |sort -u |grep -v ':\|global' |sed 's/\[\|\]//g' | tr '\n' ' ' )
+  else
+    BACKREST_STANZAS=$(grep '^\[' /etc/pgbackrest/  -rh |sort -u |grep -v ':\|global' |sed 's/\[\|\]//g' | tr '\n' ' ' )
+  fi
```
Comment (pgguru) [inline postgres_exporter/linux/pgbackrest-info.sh:23]:
```suggestion
  BACKREST_STANZAS=$(grep '^\[' /etc/pgbackrest.conf /etc/pgbackrest/  -srh |sort -u |grep -v ':\|global' |sed 's/\[\|\]//g' | tr '\n' ' ' )```

Comment (pgguru) [reply postgres_exporter/linux/pgbackrest-info.sh:23]: The `-s` flag suppresses the `file not found` messages from grep, everything else should be the same, yes?

Comment (keithf4) [reply postgres_exporter/linux/pgbackrest-info.sh:23]: oh nice! Yeah that was basically the only issue here.

**Review by jchancojr — APPROVED** [review]

**Review by hunleyd — APPROVED** [review]

**Review by pgguru — APPROVED** [review]
